#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const rootDir = path.resolve(__dirname, '..');
const pkgPath = path.join(rootDir, 'package.json');
const pkgLockPath = path.join(rootDir, 'package-lock.json');
const versionTsPath = path.join(rootDir, 'src', 'lib', 'version.ts');

function bumpPatchVersion(version) {
  const match = version.match(/^(\d+)\.(\d+)\.(\d+)$/);
  if (!match) {
    throw new Error(`Invalid version format: "${version}". Expected format: X.Y.ZZZ (e.g. 1.0.001)`);
  }
  const major = match[1];
  const minor = match[2];
  const patchStr = match[3];

  const patchNum = parseInt(patchStr, 10);
  const nextPatchNum = patchNum + 1;
  const minDigits = Math.max(patchStr.length, 3);
  const nextPatchStr = String(nextPatchNum).padStart(minDigits, '0');

  return `${major}.${minor}.${nextPatchStr}`;
}

function updateVersionFiles(newVersion, shouldStage = true) {
  // Update package.json
  if (fs.existsSync(pkgPath)) {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    pkg.version = newVersion;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
  }

  // Update package-lock.json if present
  if (fs.existsSync(pkgLockPath)) {
    try {
      const lock = JSON.parse(fs.readFileSync(pkgLockPath, 'utf8'));
      lock.version = newVersion;
      if (lock.packages && lock.packages['']) {
        lock.packages[''].version = newVersion;
      }
      fs.writeFileSync(pkgLockPath, JSON.stringify(lock, null, 2) + '\n', 'utf8');
    } catch (err) {
      console.warn('[bump-version] Warning: Could not update package-lock.json:', err.message);
    }
  }

  // Update src/lib/version.ts
  const versionTsContent = `// This file is auto-generated by scripts/bump-version.js\nexport const APP_VERSION = '${newVersion}';\n`;
  fs.writeFileSync(versionTsPath, versionTsContent, 'utf8');

  if (shouldStage) {
    try {
      const filesToStage = ['src/lib/version.ts'];
      if (fs.existsSync(pkgPath)) {
        filesToStage.push('package.json');
      }
      if (fs.existsSync(pkgLockPath)) {
        filesToStage.push('package-lock.json');
      }
      execSync(`git add ${filesToStage.join(' ')}`, { cwd: rootDir, stdio: 'inherit' });
    } catch (err) {
      console.warn('[bump-version] Warning: Failed to git add version files:', err.message);
    }
  }
}

function main() {
  const args = process.argv.slice(2);

  // Read current version preferentially from src/lib/version.ts or package.json
  let currentVersion = '1.0.001';
  if (fs.existsSync(versionTsPath)) {
    const content = fs.readFileSync(versionTsPath, 'utf8');
    const match = content.match(/APP_VERSION\s*=\s*['"]([^'"]+)['"]/);
    if (match) {
      currentVersion = match[1];
    }
  } else if (fs.existsSync(pkgPath)) {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    currentVersion = pkg.version;
  }

  if (args.includes('--current') || args.includes('-v')) {
    console.log(currentVersion);
    return;
  }

  const setIndex = args.indexOf('--set');
  if (setIndex !== -1 && args[setIndex + 1]) {
    const targetVersion = args[setIndex + 1];
    updateVersionFiles(targetVersion, true);
    console.log(`[bump-version] Version set to: ${targetVersion}`);
    return;
  }

  const nextVersion = bumpPatchVersion(currentVersion);
  updateVersionFiles(nextVersion, true);
  console.log(`[bump-version] Version bumped: ${currentVersion} -> ${nextVersion}`);
}

main();
